name: CI
on:
  pull_request: { branches: [ main ] }
  push:         { branches: [ main ] }
jobs:
  validate-compose:
    runs-on: ubuntu-latest
    env:
      ENV_FILE: env/base.env.example
    steps:
      - uses: actions/checkout@v4
      - run: docker compose -f docker-compose.yml config -q
